#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-own"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d47f9b3298e7476ea33736649bb6d0f6" }
]

[assets]
directory = "./public"
